---

- name: Ensure compilers can install
  lineinfile:
    dest=/etc/yum.conf
    state=present
    regexp='^exclude=(.*)kernel\*'
    line='#exclude=kernel*'
    insertafter='\[main\]'
    owner=root
    group=root
    mode=0644
  when: php_pecl_ext|length > 0

- name: Ensure compilers are available if pecl extensions need them
  yum:
    name="{{ item }}"
    state=present
  with_items:
    - make
    - gcc
    - zlib-devel
  when: php_pecl_ext|length > 0

- name: rollback the configuration of yum.conf
  lineinfile:
    dest=/etc/yum.conf
    state=present
    regexp='^#exclude=(.*)kernel\*'
    line='exclude=kernel*'
    insertafter='\[main\]'
    owner=root
    group=root
    mode=0644

- name: Ensure extra php extensions via pecl
  shell:
    creates="/root/.{{ item }}"
    printf "\n" | pecl install {{ item | replace("php-", "") }} | tee -a /root/.php_{{ item | replace("php-", "") }} && echo 'extension = {{ item | replace("php-", "") }}.so' > /etc/php.d/{{ item | replace("php-", "") }}.ini
  with_items:
    php_pecl_ext
  notify:
    - restart php-fpm

- name: Enable php-fpm at boot
  service:
    name=php-fpm
    enabled=yes
  when: "'php-fpm' in php_ext"

# php running user/group
- name: Ensure php process_group created
  group:
    name="{{ php_fpm_process_group }}"
    state=present

- name: Ensure php process_user created
  user:
    name={{ php_fpm_process_user }}
    group={{ php_fpm_process_group }}
    state=present
    createhome=no


- name: ensure php configuration
  template:
    src={{ php_template_version }}/php.ini.j2
    dest=/etc/php.ini
    owner=root
    group=root
    mode=0644
  notify:
    - restart php-fpm
  when:
    php_version | int < 100


- name: ensure php-fpm configuration
  template: 
    src={{ php_template_version }}/www.conf.j2
    dest=/etc/php-fpm.d/www.conf
    owner=root
    group=root
    mode=0644
  when:
    "'php-fpm' in php_ext"
  notify:
    - restart php-fpm

- name: Ensure php-fpm is running
  service:
    name=php-fpm
    state=started
  when:
    "'php-fpm' in php_ext"
