---

# We rely on REMI rpm repo
- name: Ensure EPEL/REMI repos are present for PHP > 5.3
  yum:
    name={{ item }}
    state=present
  with_items:
    - http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
  when:
    php_version|int > 53 and php_version|int < 100

# 5.3 - centalt is enabled - no need for custom enablerepo
- name: Ensure php required extensions are installed
  yum:
    name={{ item }}
    state=present
    enablerepo=amzn-main,amzn-updates
  with_flattened:
    - php-pear
    - php-common
    - php-devel
    - php
    - "{{ php_ext }}"
  when: php_version|int == 53

# install dependency package are installed
- name: Ensure dependency package are installed
  yum:
    name=httpd
    enablerepo=amzn-main,amzn-updates
    state=present
  when: php_version|int > 54

- name: Ensure dependency package are installed(gd-last)
  yum:
    name=gd-last
    enablerepo=amzn-main,amzn-updates
    state=present
  when: php_version|int == 55

# 5.4 is default in REMI repo
- name: Ensure php required extensions are installed
  yum:
    name={{ item }}
    disablerepo=amzn-main,amzn-updates
    enablerepo=remi,epel
    state=present
  with_flattened:
    - php-pear
    - php-common
    - php-devel
    - php
    - "{{ php_ext }}"
  when: php_version|int == 54

# 5.5 is available in amzn-updates
- name: Ensure php required extensions are installed
  yum:
    name={{ item }}
    disablerepo=amzn-main,amzn-updates
    enablerepo=remi-php55,epel
    state=present
  with_flattened:
    - php-pear
    - php-common
    - php-devel
    - php
    - "{{ php_ext }}"
  when: php_version|int == 55

# 5.6 is available in remi-php56
- name: Ensure php required extensions are installed
  yum:
    name={{ item }}
    disablerepo=amzn-main,amzn-updates
    enablerepo=remi,remi-php56,epel
    state=present
  with_flattened:
    - php-pear
    - php-common
    - php-devel
    - php
    - "{{ php_ext }}"
  when: php_version|int == 56

