---

# We rely on REMI rpm repo
- name: Ensure EPEL/REMI repos are present for PHP > 5.3
  yum:
    name={{ item }}
    state=present
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  when:
    ansible_distribution_major_version|int == 7

# 5.5 is available in remi-php55
- name: Ensure php required extensions are installed
  yum:
    name={{ item }}
    enablerepo=remi-php55,remi,epel
    state=present
  with_flattened:
    - php-pear
    - php-common
    - php-devel
    - php
    - php-fpm
    - php-mysqlnd
    - "{{ php_ext }}"
  when:
    php_version == '5.5'

# 5.6 is available in remi-php56
- name: Ensure php required extensions are installed
  yum:
    name={{ item }}
    enablerepo=remi-php56,remi,epel
    state=present
  with_flattened:
    - php-pear
    - php-common
    - php-devel
    - php-fpm
    - php
    - "{{ php_ext }}"
  when:
    php_version == '5.6'

