---
#
# Handle iptables config
#

- name: Add iptables modules to the config
  lineinfile: 
    dest=/etc/sysconfig/iptables-config 
    regexp='^IPTABLES_MODULES='
    line='IPTABLES_MODULES="ip_conntrack_ftp"'
