---
# Install sshd-nc6 and other relevant packages and modify config files

- name: Install packages for LDAP login sshd-nc, nss-pam-ldap and openldap-clients
  yum:
    name="{{ item }}"
    state=latest
  with_items:
    - nss-pam-ldapd
    - openldap-clients
    - sshd-nc6

- name: Install openssh-ldap for Centos-7
  yum:
   name: openssh-ldap
   state: present
  when:
    ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Create directory for LDAP certificates
  file:
    path=/etc/openldap/cacerts
    state=directory

- name: Copy LDAP certificates
  copy:
    backup=yes
    force=yes
    src={{ item.src }}
    dest={{ item.dest }}
    mode=0444
    owner=root
    group=root
  with_items:
    - { src: 'files/openldap-certs-9b28ab84.0', dest: '/etc/openldap/cacerts/9b28ab84.0' }
    - { src: 'files/openldap-certs-a54a9db1.0', dest: '/etc/openldap/cacerts/a54a9db1.0' }
    - { src: 'files/openldap-certs-cnc_ca_ldap_cert.pem', dest: '/etc/openldap/cacerts/cnc_ca_ldap_cert.pem' }
    - { src: 'files/openldap-certs-cnc_ca_root_cert.pem', dest: '/etc/openldap/cacerts/cnc_ca_root_cert.pem' }

- name: Copy nslcd.conf
  copy:
    backup=yes
    force=yes
    src=files/nslcd.conf
    dest=/etc/nslcd.conf
    mode=0600
    owner=root
    group=root

- name: Copy ldap.conf
  template:
    backup=yes
    force=yes
    src=templates/ldap.conf.j2
    dest=/etc/ldap.conf
    mode=0644
    owner=root
    group=root

- name: Backup pam_ldap.conf
  command: 
    creates=/etc/pam_ldap.conf.bck
    mv /etc/pam_ldap.conf /etc/pam_ldap.conf.bck
  when:
    ansible_distribution != "CentOS" and ansible_distribution_major_version != "7" 

- name: Define sshd-nc systemd service
  file:
    src=files/sshd-nc.service
    dest=/usr/lib/systemd/system/sshd-nc.service
    mode=0644
  when:
    ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Delete /etc/init.d/sshd-nc service script(el7)
  file:
    path=/etc/rc.d/init.d/sshd-nc
    state=absent
  when:
    ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
    
- name: Link ldap.conf to pam_ldap.conf
  file:
    src=/etc/ldap.conf
    dest=/etc/pam_ldap.conf
    force=yes
    state=link
  when:
    ansible_distribution == 'Amazon' or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 6)
  notify:
    - Start nslcd
    - Start sshd-nc
    - Disable nscd
    - Enable sshd-nc
    - Enable nslcd

## notify function has some instability on centos 7, so defined restart service tasks.
- name: Restart nslcd
  service:
    name=nslcd
    state=restarted
    enabled=yes
- name: Restart sshd-nc
  service:
    name=sshd-nc
    state=restarted
    enabled=yes
- name: Disabled nscd
  service:
    name=nscd
    state=stopped
    enabled=no

- name: Ensure sudo permissions for LDAP Groups
  template:
    src=templates/ldapgroups.conf.j2
    dest=/etc/sudoers.d/ldapgroups
    owner=root
    group=root
    mode=0440

- name: Ensure LDAP enabled for passwd service
  lineinfile:
    dest=/etc/nsswitch.conf
    state=present
    regexp='^passwd:'
    line="passwd{{':'}}     files ldap"

- name: Ensure LDAP enabled for shadow service
  lineinfile:
    dest=/etc/nsswitch.conf
    state=present
    regexp='^shadow:'
    line="shadow{{':'}}     files ldap"

- name: Ensure LDAP enabled for group service
  lineinfile:
    dest=/etc/nsswitch.conf
    state=present
    regexp='^group:'
    line="group{{':'}}      files ldap"
