---
- name: Ensure rsyslog configuration
  template:
    src=rsyslog.conf.j2
    dest=/etc/rsyslog.conf
    owner=root
    group=root
    backup=yes
    mode=0644
  notify:
     - Restart rsyslog

- name: Ensure rsyslog.d directory exist
  file:
    path=/etc/rsyslog.d
    state=directory

- name: Ensure rsyslog cmd_track configuration
  copy:
    src=10-cmd_track.conf
    dest=/etc/rsyslog.d/10-cmd_track.conf
    owner=root
    group=root
    mode=0644
  notify:
     - Restart rsyslog

- name: Ensure rsyslog is running
  service:
    name=rsyslog
    state=started
