---
# 
# Handle SSH custom config
# 

- name: '[SSH] Ensure port 40022 is enabled'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    line='Port 40022'
    insertafter='#Port 22'
  notify:
    Restart ssh

- name: '[SSH] Ensure port 22 is disabled'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=absent
    regexp='^(Port 22)$'
  notify:
    Restart ssh

- name: '[SSH] root login is disabled(rhel6/amzn)'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    line='PermitRootLogin no'
    insertafter='#PermitRootLogin yes'
  when:
    ansible_distribution == "Amazon" or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6)
  notify:
    Restart ssh

- name: '[SSH] root login is disabled(rhel7)'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=absent
    line='PermitRootLogin yes'
  when:
    ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  notify:
    Restart ssh

- name: '[SSH] allow password auth - step1'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=absent
    line='PasswordAuthentication no'
  notify:
    Restart ssh

- name: '[SSH] allow password auth - step2'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    line='PasswordAuthentication yes'
  notify:
    Restart ssh

- name: '[SSH] NC_ENV is allowed'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    line='AcceptEnv NC_ENV'
    insertafter='AcceptEnv XMODIFIERS'
  notify:
    Restart ssh

- name: '[SSH] Disable UseDNS'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    line='UseDNS no'
    insertafter='#UseDNS yes'
  notify:
    Restart ssh

- name: '[SSH] Enforce sshers group'
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    line='AllowGroups sshers'
  notify:
    Restart ssh
