---
- name: Ensure sysctl settings are properly applied (common)
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state=present
    reload=yes
    sysctl_set=no
    ignoreerrors=yes
  with_dict: 
    "{{ sysctl_common }}"

- name: Ensure sysctl settings are properly applied (CentOS5)
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state=present
    reload=yes
    sysctl_set=no
    ignoreerrors=yes
  with_dict: 
    "{{ sysctl_centos5 }}"
  when: 
    ansible_distribution != 'Amazon' and ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 6

- name: Ensure sysctl settings are properly applied (CentOS6)
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state=present
    reload=yes
    sysctl_set=no
    ignoreerrors=yes
  with_dict: 
    "{{ sysctl_centos6 }}"
  when: 
    ansible_distribution == 'Amazon' or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6)

- name: Ensure sysctl settings are properly applied
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state=present
    reload=yes
    sysctl_set=no
    ignoreerrors=yes
  with_dict:
    "{{ sysctl_centos7 }}"
  when:
    ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Ensure sysctl settings are properly applied (CentOS7)
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state=present
    reload=yes
    sysctl_set=no
    ignoreerrors=yes
  with_dict:
    "{{ sysctl_centos7 }}"
  when:
    ansible_distribution == "CentOS" and ansible_distribution_major_version == 7
