---
- name: Ensure the linux groups
  group:
    name="{{ item }}"
    state=present
  with_items: 
    "{{ linux_groups }}"

- name: Create the linux users
  user:
    name={{ item.key }}
    group={{ item.value.group }}
    groups={% if item.value.groups is defined %}{{ item.value.groups }}{% endif %}
    password={% if item.value.password is defined %}{{ item.value.password }}{% endif %}
    shell={{ item.value.shell | default('/sbin/nologin') }}
    state=present
    update_password=on_create
  with_dict: 
    "{{ linux_users }}"

- name: Ensure sudo permissions for NetCloud users
  template:
    src=sudoers.conf.j2
    dest=/etc/sudoers.d/{{ item.key }}
    owner=root
    group=root
    mode=0440
#    mode=0600
  with_dict: 
    "{{ sudoers }}"

- name: Ensure NC_USER env var is propagated on sudo
  lineinfile:
    dest=/etc/sudoers
    state=present
    insertafter='Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"'
    line='Defaults    env_keep += "NC_USER"'
