---

# Set some variables that are used throughout the playbook
# These should be dynamic from the Design System later to handle different applications/versions
- name: Set Tomcat Major Version
  set_fact:
    fact_tomcat_major_ver=7
  delegate_to: 127.0.0.1
  when:
    tomcat_version == 'Tomcat 7'

- name: Set Tomcat Minor Version
  set_fact:
    fact_tomcat_minor_ver='7.0.81'
  delegate_to: 127.0.0.1
  when:
    tomcat_version == 'Tomcat 7'

- name: Set Tomcat Major Version
  set_fact:
    fact_tomcat_major_ver=8
  delegate_to: 127.0.0.1
  when:
    tomcat_version == 'Tomcat 8'

- name: Set Tomcat Minor Version
  set_fact:
    fact_tomcat_minor_ver='8.5.21'
  delegate_to: 127.0.0.1
  when:
    tomcat_version == 'Tomcat 8'

# Conditionally decide to load in variables when x is 0, otherwise do not.
#- include_vars: defaults.yml

# Ensure package
- name: Download tomcat
  get_url:
    url=http://mirror.bit.edu.cn/apache/tomcat/tomcat-{{ fact_tomcat_major_ver }}/v{{ fact_tomcat_minor_ver }}/bin/apache-tomcat-{{ fact_tomcat_minor_ver }}.tar.gz
    dest=/opt/apache-tomcat-{{ fact_tomcat_minor_ver }}.tar.gz
- name: Unarchive Tomcat
  unarchive:
    copy=no
    src=/opt/apache-tomcat-{{ fact_tomcat_minor_ver }}.tar.gz
    dest=/opt/
- name: Symlink Tomcat Directory
  file:
    src=/opt/apache-tomcat-{{ fact_tomcat_minor_ver }}
    dest=/opt/tomcat
    state=link

# Create user and group
- name: Create the tomcat group
  group:
    name=tomcat
    state=present
    system=yes
- name: Create the tomcat user
  user:
    name=tomcat
    group=tomcat
    system=yes
    state=present

# Change owner of tomcat directory
- name: Change owner of tomcat application files
  file:
    dest=/opt/apache-tomcat-{{ fact_tomcat_minor_ver }}
    owner=tomcat
    group=tomcat
    recurse=yes
    state=directory

# Ensure change start script's name
- name: Change startup.sh to initiate.sh
  command:
    removes=/opt/tomcat/bin/startup.sh
    mv /opt/tomcat/bin/startup.sh /opt/tomcat/bin/initiate.sh

# Ensure add new startup script
- name: Ensure add new startup script
  template:
    src=startup.sh.j2
    dest=/opt/tomcat/bin/
    owner=tomcat
    group=tomcat
    mode=0755

# Add startup scripts
- name: Ensure Tomcatd start script
  template:
    src=tomcatd.j2
    dest={{ tomcat_init_script }}
    owner=root
    group=root
    mode=0755
- name: Ensure Tomcat sysconfig configuration
  template:
    src=tomcat.j2
    dest={{ tomcat_config_file }}
    owner=root
    group=root
    mode=0644


# Configure jmx authentication
- name: Ensure JMX Access file
  template:
    src=jmxremote.access.j2
    dest={{ tomcat_catalina_home }}/conf/jmxremote.access
    owner=tomcat
    group=tomcat
    mode=0600
- name: Ensure JMX Password file
  template:
    src=jmxremote.passwd.j2
    dest={{ tomcat_catalina_home }}/conf/jmxremote.passwd
    owner=tomcat
    group=tomcat
    mode=0600

- name: Configure Tomcat Logrotate
  template:
    src=tomcat_logrotate
    dest=/etc/logrotate.d/tomcat
    owner=root
    group=root
    mode=0644

# Enable tomcat service, and start
- name: Enable Tomcat at boot
  service:
    name=tomcat
    enabled=yes

- name: Ensure hosts record is exists
  lineinfile:
    dest=/etc/hosts
    line="127.0.0.1 {{ ansible_hostname }}" 
    state=present
    
- name: Ensure Tomcat is running
  service:
    name=tomcat
    pattern="-Dcatalina.home={{ tomcat_catalina_home }}"
    state=started