---
- name: start haproxy
  service:
    name=haproxy
    state=started
- name: restart haproxy
  service:
    name=haproxy
    state=restarted
- name: stop haproxy
  service:
    name=haproxy
    state=stopped

- name: restart rsyslog
  service:
    name=rsyslog
    state=restarted
