---
#- include_vars: defaults.yml
- name: Register backup destination
  set_fact:
    ncbackup_storage_method=OSS
  delegate_to: 127.0.0.1
  when:
    backup_destination == 'OSS'

- name: Register backup destination
  set_fact:
    ncbackup_storage_method=S3
  delegate_to: 127.0.0.1
  when:
    backup_destination == 'S3'

- name: Register backup destination
  set_fact:
    ncbackup_storage_method=SSH
  delegate_to: 127.0.0.1
  when:
    backup_destination == 'Customer Storage'

- name: Check backup folder if exist
  stat:
    path=/opt/ncscripts/backup
  register: checkfolder

- name: Download Netcloud Backup Scripts from Git
  git:
    repo=https://nc-git-ansible:{{ git_ansible_pass }}@gitlab.service.chinanetcloud.com/backup/ncbackup.git
    dest=/opt/ncscripts/backup
    force=yes
    accept_hostkey=yes
  when:
    not checkfolder.stat.exists == True

- name: Delete .git folder, avoid git password being hacked
  file: path=/opt/ncscripts/backup/.git state=absent

- name: Insert GPG_KEY into backup key_file
  copy: content="{{ gpg_key }}" dest=/opt/ncscripts/backup/key_file


- name: Set permission for Backup Scripts
  file:
    dest=/opt/ncscripts/backup
    owner=ncbackup
    group=ncbackup
    recurse=yes
    state=directory

- name: Ensure execute permissions for backup scripts
  file:
    dest=/opt/ncscripts/backup/scripts-available
    mode=0755
    recurse=yes
    state=directory

- name: Ensure permissions for /opt/backup
  file:
    dest=/opt/backup
    owner=ncbackup
    group=ncbackup
    recurse=yes
    state=directory

- name: Ensure backup configuration
  template:
    src=ncbackup.conf.j2
    dest=/opt/ncscripts/backup/conf/{{ inventory_hostname }}.conf
    owner=ncbackup
    group=ncbackup
    mode=0644

- name: Set Active database backup script
  file:
    src=/opt/ncscripts/backup/scripts-available/mydump_script_backup.sh
    dest=/opt/ncscripts/backup/scripts-enabled/mydump_script_backup.sh
    state=link
  when:
    database_mysql_backup == 'Yes'

# Install Aliyun server tools, depending on backup type
- name: Install Aliyun backup server tools
  yum:
    name=aliyun-oss-tools
    state=present
  when:
    ncbackup_storage_method == 'OSS'

- name: Make Aliyun binary executable
  file:
    dest=/usr/bin/alicmd
    mode=0755
  when:
    ncbackup_storage_method == 'OSS'

- name: Configure Aliyun OSS tool
  template:
    src=alioss.conf.j2
    dest=/etc/.alioss.conf
    owner=root
    group=root
    mode=0644
  when:
    ncbackup_storage_method == 'OSS'

- name: Ensure cron job for backup script
  cron:
    name="ncbackup-master"
    hour="3"
    minute="0"
    user="ncbackup"
    job="TZ='Asia/Shanghai' bash /opt/ncscripts/backup/master_backup_script.sh --run --config /opt/ncscripts/backup/conf/$HOSTNAME.conf"
    state="present"

- name: Ensure cron job for backup-cleanup script
  cron:
    name="ncbackup-cleanup"
    hour="3"
    minute="30"
    user="ncbackup"
    job="TZ='Asia/Shanghai' bash /opt/ncscripts/backup/clean_local_backup.sh"
    state="present"
