---
################
# File system management
################

- name: Set datadir root
  set_fact:
    fact_httpd_datadir={% if not server_enable_lvm %}/var/www{% else %}{{ httpd_lvm_lv_mountpoint }}{% endif %}
  delegate_to: 127.0.0.1

- name: create lvm for httpd
  lvol:
    vg={{ httpd_lvm_vg_name }}
    lv={{ httpd_lvm_lv_name }}
    size={{ httpd_lvm_lv_size }}
    state=present
  when: server_enable_lvm

- name: ensure httpd root folder
  file:
    dest={{ fact_httpd_datadir }}
    owner=root
    group=root
    state=directory

- name: make filesystem for httpd
  filesystem:
    fstype={{ httpd_lvm_lv_fstype }}
    dev=/dev/{{ httpd_lvm_vg_name }}/{{ httpd_lvm_lv_name }}
  when: server_enable_lvm

- name: mount httpd root folder
  mount:
    name={{ fact_httpd_datadir }}
    src=/dev/{{ httpd_lvm_vg_name }}/{{ httpd_lvm_lv_name }}
    fstype={{ httpd_lvm_lv_fstype }}
    opts={{ httpd_lvm_lv_mountpoint_options | default('') | replace(';',',') }}
    state=mounted
  when: server_enable_lvm


################
# Setup phase
################
- name: ensure httpd is installed
  yum:
    name=httpd
    state=present

- name: Ensure httpd start at boot
  service:
    name=httpd
    enabled=yes

# Cheat and hardcode version
- name: Register httpd version
  set_fact:
    httpd_template_version="{{ apache_version }}"
  delegate_to: 127.0.0.1

- name: Ensure httpd configuration
  template:
    src="{{ httpd_template_version }}/httpd.conf.j2"
    dest="/etc/httpd/httpd.conf"
    owner=root
    group=root
    mode=0644
  notify:
    - restart httpd

- name: ensure httpd vhost configuration
  template:
    src="{{ httpd_template_version }}/vhost.conf.j2"
    dest="/etc/httpd/conf.d/{{ item.domain }}.conf"
    owner=root
    group=root
    mode=0644
  with_items:
    "{{ httpd_vhosts }}"
  notify:
    - restart httpd

- name: ensure httpd monitoring configuration
  template:
    src="{{ httpd_template_version }}/zabbix.conf.j2"
    dest=/etc/httpd/conf.d/zabbix.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart httpd

- name: ensure vhost log folder and create log folder
  file:
    dest="/var/log/httpd/{{ item.domain }}"
    owner=root
    group=root
    state=directory
  with_items:
    "{{ httpd_vhosts }}"

- name: ensure vhost data folder and create data folder
  file:
    dest="{{ fact_httpd_datadir }}/sites/{{ item.domain }}"
    owner=root
    group=root
    state=directory
  with_items:
    "{{ httpd_vhosts }}"

- name: ensure 404 error page is configured
  copy:
    src=404.html
    dest="{{ fact_httpd_datadir }}/sites/{{ item.domain }}/404.html"
  with_items:
    "{{ httpd_vhosts }}"

- name: ensure 5xx error page is configured
  copy:
    src=5xx.html
    dest="{{ fact_httpd_datadir }}/sites/{{ item.domain }}/5xx.html"
  with_items:
    "{{ httpd_vhosts }}"

- name: ensure logrotate is properly set for httpd
  template:
    src={{ httpd_template_version }}/httpd.logrotate.j2
    dest=/etc/logrotate.d/httpd
    owner=root
    group=root
    mode=0644

- name: Ensure httpd is running
  service:
    name=httpd
    state=started
