---
- name: Ensure haproxy is installed
  yum:
    name=haproxy
    state=present

- name: Enable HaProxy at boot
  service:
    name=haproxy
    enabled=yes
    
- name: Configure HaProxy
  template:
    src=haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
    owner=root
    group=root
    mode=0644
  notify:
  - restart haproxy

- name: Configure Haproxy Logrotate
  template:
    src=haproxy_logrotate
    dest=/etc/logrotate.d/haproxy
    owner=root
    group=root
    mode=0644

- name: Ensure HaProxy is running
  service:
    name=haproxy
    state=running

# Using rsyslog
- name: Ensure rsyslog configuration
  copy:
    src=20-haproxy.conf
    dest=/etc/rsyslog.d/20-haproxy.conf
  notify:
    - restart rsyslog

- name: Download cnc-haproxy- scripts use git
  git:
    repo=https://nc-git-ansible:{{ git_ansible_pass }}@gitlab.service.chinanetcloud.com/nc-scripts/haproxy.git
    dest=/opt/ncscripts/haproxy
    accept_hostkey=yes
    force=yes

- name: Ensure cnc-haproxy- scripts permission
  file:
    src="{{ item.src }}"
    dest="{{ item.dest }}"
    state=link
  with_items:
    - src: /opt/ncscripts/haproxy/cnc-haproxy-console
      dest: /sbin/cnc-haproxy-console
    - src: /opt/ncscripts/haproxy/cnc-haproxy-status
      dest: /sbin/cnc-haproxy-status

- name: Ensure socat package installed
  yum:
    name=socat
    state=present
